---
platform: linux
image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
  - name: greenpeace
  - name: tfstate

params:
  TARGET:
  DATADOG_API_KEY:
  DATADOG_APP_KEY:

run:
  path: greenpeace/pipelines/tasks/scripts/terraform-plan
