jobs:
  - name: ci-dashboard-changes
    serial: true
    plan:
      - get: once-a-week
        trigger: true
      - get: greenpeace
      - task: import-tfstate
        file: greenpeace/pipelines/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.ci_dashboard.datadog_dashboard.concourse
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse Dashboard - CI"
      - task: terraform-plan
        file: greenpeace/pipelines/tasks/terraform-plan.yml
        params:
          TARGET: module.ci_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

  - name: ci-bosh-dashboard-changes
    serial: true
    plan:
      - get: once-a-week
        trigger: true
      - get: greenpeace
      - task: import-tfstate
        file: greenpeace/pipelines/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.ci_bosh_dashboard.datadog_dashboard.concourse
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse Dashboard - CI - BOSH"
      - task: terraform-plan
        file: greenpeace/pipelines/tasks/terraform-plan.yml
        params:
          TARGET: module.ci_bosh_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

  - name: hush-house-dashboard-changes
    serial: true
    plan:
      - get: once-a-week
        trigger: true
      - get: greenpeace
      - task: import-tfstate
        file: greenpeace/pipelines/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.hush_house_dashboard.datadog_dashboard.concourse
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse Dashboard - Hush House"
      - task: terraform-plan
        file: greenpeace/pipelines/tasks/terraform-plan.yml
        params:
          TARGET: module.ci_bosh_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

resources:
  - name: greenpeace
    type: git
    source:
      uri: git@github.com:pivotal-izabela-gomes/observability-config.git
      branch: master
      private_key: ((concourse_bot_private_key))

  - name: once-a-week
    type: time
    source:
      interval: 30m
      start: 9:00 PM
      stop: 10:00 PM
      location: America/Toronto
      days: [Tuesday]

#  - name: greenpeace
#    type: git
#    source:
#      uri: git@github.com:concourse/hush-house.git
#      branch: greenpeace
#      private_key: ((concourse_bot_private_key))
