jobs:
  - name: ci-dashboard-changes
    serial: true
    plan:
      - get: every-other-day
        trigger: true
      - get: ci
      - get: greenpeace
      - task: import-tfstate
        file: ci/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.ci_dashboard.datadog_dashboard.concourse
          RESOURCE_ADDRESS_SYSSTAS: module.ci_dashboard.datadog_dashboard.concourse_systemstats
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse - CI"
      - task: terraform-plan
        file: ci/tasks/terraform-plan.yml
        params:
          TARGET: module.ci_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

  - name: ci-bosh-dashboard-changes
    serial: true
    plan:
      - get: every-other-day
        trigger: true
      - get: ci
      - get: greenpeace
      - task: import-tfstate
        file: ci/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.ci_bosh_dashboard.datadog_dashboard.concourse
          RESOURCE_ADDRESS_SYSSTAS: module.ci_bosh_dashboard.datadog_dashboard.concourse_systemstats_bosh
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse - CI - BOSH"
      - task: terraform-plan
        file: ci/tasks/terraform-plan.yml
        params:
          TARGET: module.ci_bosh_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

  - name: hush-house-dashboard-changes
    serial: true
    plan:
      - get: every-other-day
        trigger: true
      - get: ci
      - get: greenpeace
      - task: import-tfstate
        file: ci/tasks/import-tfstate.yml
        params:
          RESOURCE_ADDRESS: module.hush_house_dashboard.datadog_dashboard.concourse
          RESOURCE_ADDRESS_SYSSTAS: module.hush_house_dashboard.datadog_dashboard.concourse_systemstats
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))
          DASHBOARD_TITLE: "Concourse - Hush House"
      - task: terraform-plan
        file: ci/tasks/terraform-plan.yml
        params:
          TARGET: module.hush_house_dashboard
          DATADOG_API_KEY: ((datadog_api_key))
          DATADOG_APP_KEY: ((datadog_app_key))

resources:
  - name: greenpeace
    type: git
    source:
      uri: git@github.com:concourse/greenpeace.git
      branch: master
      private_key: ((concourse_bot_private_key))

  - name: ci
    type: git
    source:
      uri: git@github.com:pivotal-izabela-gomes/observability-config.git
      branch: master
      private_key: ((concourse_bot_private_key))

  - name: every-other-day
    type: time
    source:
      interval: 48h

#  - name: greenpeace
#    type: git
#    source:
#      uri: git@github.com:concourse/hush-house.git
#      branch: greenpeace
#      private_key: ((concourse_bot_private_key))
